### ISSUE TITLE
Arabidopsis_suecica_LTR.inner.fa.cls.tsv not found

### ISSUE THREAD

**Issue by kfuku52** [zhangrengang/SubPhaser#13]
Thank you for developing this excellent tool! I installed SubPhaser in a singularity container with the minimal dependencies listed in https://github.com/zhangrengang/SubPhaser/issues/10#issuecomment-1338966967 and tried to run the Arabidopsis test dataset, but an error occurred. Another run with my own dataset stopped with the same error message. I would be grateful if you could provide me with potential solutions.

```
22-12-18 06:54:20 [INFO] finished with 0 commands uncompleted
22-12-18 06:54:20 [INFO] New check point file: `/home/kfuku/docker_img/gfe/usr/local/bin/SubPhaser/example_data/Arabidopsis_suecica_tmp/Arabidopsis_suecica_LTR.scn.ok`
22-12-18 06:54:20 [INFO] 5566 LTRs identified
22-12-18 06:54:20 [INFO] Extracting inner sequences of LTRs to classify by `TEsorter`
22-12-18 06:54:20 [INFO] run CMD: `TEsorter /home/kfuku/docker_img/gfe/usr/local/bin/SubPhaser/example_data/Arabidopsis_suecica_tmp/Arabidopsis_suecica_LTR.inner.fa -db rexdb -dp2 -p 128 -pre /home/kfuku/docker_img/gfe/usr/local/bin/SubPhaser/example_data/Arabidopsis_suecica_tmp/Arabidopsis_suecica_LTR.inner.fa -tmp /home/kfuku/docker_img/gfe/usr/local/bin/SubPhaser/example_data/Arabidopsis_suecica_tmp/Arabidopsis_suecica_LTR &> /home/kfuku/docker_img/gfe/usr/local/bin/SubPhaser/example_data/Arabidopsis_suecica_tmp/Arabidopsis_suecica_LTR.inner.fa.tesort.log`
22-12-18 06:54:56 [INFO] New check point file: `/home/kfuku/docker_img/gfe/usr/local/bin/SubPhaser/example_data/Arabidopsis_suecica_tmp/Arabidopsis_suecica_LTR.tesort.ok`
Traceback (most recent call last):
  File "/opt/conda/envs/biotools/bin/subphaser", line 33, in <module>
    sys.exit(load_entry_point('subphaser==1.2.5', 'console_scripts', 'subphaser')())
  File "/opt/conda/envs/biotools/lib/python3.9/site-packages/subphaser-1.2.5-py3.9.egg/subphaser/__main__.py", line 784, in main
    pipeline.run()
  File "/opt/conda/envs/biotools/lib/python3.9/site-packages/subphaser-1.2.5-py3.9.egg/subphaser/__main__.py", line 518, in run
    ltr_bedlines, enrich_ltr_bedlines = self.step_ltr(d_kmers) if not self.disable_ltr else ([],[])
  File "/opt/conda/envs/biotools/lib/python3.9/site-packages/subphaser-1.2.5-py3.9.egg/subphaser/__main__.py", line 556, in step_ltr
    ltrs, ltrfile = pipeline.run()
  File "/opt/conda/envs/biotools/lib/python3.9/site-packages/subphaser-1.2.5-py3.9.egg/subphaser/LTR.py", line 335, in run
    d_class = self.classfify(ltrs)
  File "/opt/conda/envs/biotools/lib/python3.9/site-packages/subphaser-1.2.5-py3.9.egg/subphaser/LTR.py", line 397, in classfify
    for classification in CommonClassifications(clsfile):
  File "/opt/conda/envs/biotools/lib/python3.9/site-packages/subphaser-1.2.5-py3.9.egg/subphaser/api/TEsorter/app.py", line 339, in _parse
    for i, line in enumerate(open(self.clsfile)):
  File "/opt/conda/envs/biotools/lib/python3.9/site-packages/xopen/__init__.py", line 1291, in xopen
    opened_file = open(filename, mode, **text_mode_kwargs)  # type: ignore
FileNotFoundError: [Errno 2] No such file or directory: '/home/kfuku/docker_img/gfe/usr/local/bin/SubPhaser/example_data/Arabidopsis_suecica_tmp/Arabidopsis_suecica_LTR.inner.fa.cls.tsv'
```

**Comment by zhangrengang** [comment]
@kfuku52 It seems incompleteness of TEsorter. Can you provide me the log file `/home/kfuku/docker_img/gfe/usr/local/bin/SubPhaser/example_data/Arabidopsis_suecica_tmp/Arabidopsis_suecica_LTR.inner.fa.tesort.log` and the file list via `ls -altr /home/kfuku/docker_img/gfe/usr/local/bin/SubPhaser/example_data/Arabidopsis_suecica_tmp/`?

**Comment by zhangrengang** [comment]
BTW, did you get the similar issue of #10 ? Why do you not install with the yaml?

**Comment by kfuku52** [comment]
Thank you for your response. `Arabidopsis_suecica_LTR.inner.fa.tesort.log` was created but empty (0-byte file). `ls -altr` showed:
```
total 25264
drwxr-xr-x 4 kfuku mh-nibb     4096 Dec 19 19:40 ..
-rw-r--r-- 1 kfuku mh-nibb     2546 Dec 19 19:40 Arabidopsis_suecica_split.ok
drwxr-xr-x 2 kfuku mh-nibb     4096 Dec 19 19:40 Arabidopsis_suecica_chromosomes
-rw-r--r-- 1 kfuku mh-nibb        0 Dec 19 19:41 Arabidopsis_suecica_Arabidopsis_suecica_k15_q200_f2.kmer.mat.ok
-rw-r--r-- 1 kfuku mh-nibb        0 Dec 19 19:41 Arabidopsis_suecica_Arabidopsis_suecica_k15_q200_f2.subgenome.bin.count.ok
-rw-r--r-- 1 kfuku mh-nibb        0 Dec 19 19:47 Arabidopsis_suecica_LTR.scn.ok
-rw-r--r-- 1 kfuku mh-nibb   487680 Dec 19 19:47 Arabidopsis_suecica_LTR.scn
-rw-r--r-- 1 kfuku mh-nibb        0 Dec 19 19:47 Arabidopsis_suecica_LTR.inner.fa.tesort.log
-rw-r--r-- 1 kfuku mh-nibb 25334538 Dec 19 19:47 Arabidopsis_suecica_LTR.inner.fa
drwxr-xr-x 2 kfuku mh-nibb    24576 Dec 19 19:48 Arabidopsis_suecica_LTR
-rw-r--r-- 1 kfuku mh-nibb        0 Dec 19 19:48 Arabidopsis_suecica_LTR.tesort.ok
-rw-r--r-- 1 kfuku mh-nibb        0 Dec 19 19:48 Arabidopsis_suecica_LTR.inner.fa.domtbl
drwxr-xr-x 4 kfuku mh-nibb     4096 Dec 19 19:48 .
```

**Comment by zhangrengang** [comment]
Can you `rm Arabidopsis_suecica_LTR.tesort.ok Arabidopsis_suecica_LTR.inner.fa.domtbl` and `TEsorter /home/kfuku/docker_img/gfe/usr/local/bin/SubPhaser/example_data/Arabidopsis_suecica_tmp/Arabidopsis_suecica_LTR.inner.fa -db rexdb -dp2 -p 128 -pre /home/kfuku/docker_img/gfe/usr/local/bin/SubPhaser/example_data/Arabidopsis_suecica_tmp/Arabidopsis_suecica_LTR.inner.fa -tmp /home/kfuku/docker_img/gfe/usr/local/bin/SubPhaser/example_data/Arabidopsis_suecica_tmp/Arabidopsis_suecica_LTR` to see any log printed?

**Comment by kfuku52** [comment]
Oops, hmmer doesn't seem to be configured properly. I will fix it and report if it worked.
```
(biotools) Singularity> TEsorter Arabidopsis_suecica_LTR.inner.fa -db rexdb -dp2 -p 4 -pre Arabidopsis_suecica_LTR.inner.fa -tmp Arabidopsis_suecica_LTR
2022-12-19 20:13:08,398 -WARNING- Grid computing is not available because DRMAA not configured properly: Could not find drmaa library.  Please specify its full path using the environment variable DRMAA_LIBRARY_PATH
2022-12-19 20:13:08,403 -INFO- VARS: {'sequence': 'Arabidopsis_suecica_LTR.inner.fa', 'hmm_database': 'rexdb', 'seq_type': 'nucl', 'prefix': 'Arabidopsis_suecica_LTR.inner.fa', 'force_write_hmmscan': False, 'processors': 4, 'tmp_dir': 'Arabidopsis_suecica_LTR', 'min_coverage': 20, 'max_evalue': 0.001, 'disable_pass2': True, 'pass2_rule': '80-80-80', 'no_library': False, 'no_reverse': False, 'no_cleanup': False}
2022-12-19 20:13:08,403 -INFO- checking dependencies:
2022-12-19 20:13:08,408 -ERROR- hmmer>=3.1 not found
2022-12-19 20:13:08,409 -INFO- check database rexdb
2022-12-19 20:13:08,409 -INFO- db path: /opt/conda/envs/biotools/lib/python3.9/site-packages/TEsorter/database
2022-12-19 20:13:08,409 -INFO- db file: REXdb_protein_database_viridiplantae_v3.0_plus_metazoa_v3.hmm
2022-12-19 20:13:08,409 -INFO- REXdb_protein_database_viridiplantae_v3.0_plus_metazoa_v3.hmm	OK
2022-12-19 20:13:08,409 -INFO- Start classifying pipeline
2022-12-19 20:13:09,731 -INFO- total 5566 sequences
2022-12-19 20:13:09,731 -INFO- translating `Arabidopsis_suecica_LTR.inner.fa` in six frames
/opt/conda/envs/biotools/lib/python3.9/site-packages/Bio/Seq.py:2979: BiopythonWarning: Partial codon, len(sequence) not a multiple of three. Explicitly trim the sequence or add trailing N before translation. This may become an error in future.
  warnings.warn(
2022-12-19 20:13:29,588 -INFO- HMM scanning against `/opt/conda/envs/biotools/lib/python3.9/site-packages/TEsorter/database/REXdb_protein_database_viridiplantae_v3.0_plus_metazoa_v3.hmm`
2022-12-19 20:13:30,078 -INFO- Creating server instance (pp-1.6.4.4)
2022-12-19 20:13:30,078 -INFO- Running on Python 3.9.13 linux
2022-12-19 20:13:30,297 -INFO- pp local server started with 4 workers
2022-12-19 20:13:30,317 -INFO- Task 0 started
2022-12-19 20:13:30,318 -INFO- Task 1 started
2022-12-19 20:13:30,318 -INFO- Task 2 started
2022-12-19 20:13:30,319 -INFO- Task 3 started
2022-12-19 20:13:30,329 -WARNING- Grid computing is not available because DRMAA not configured properly: Could not find drmaa library.  Please specify its full path using the environment variable DRMAA_LIBRARY_PATH
 2022-12-19 20:13:30,330 -WARNING- Grid computing is not available because DRMAA not configured properly: Could not find drmaa library.  Please specify its full path using the environment variable DRMAA_LIBRARY_PATH
 2022-12-19 20:13:30,329 -WARNING- Grid computing is not available because DRMAA not configured properly: Could not find drmaa library.  Please specify its full path using the environment variable DRMAA_LIBRARY_PATH
 2022-12-19 20:13:30,330 -WARNING- Grid computing is not available because DRMAA not configured properly: Could not find drmaa library.  Please specify its full path using the environment variable DRMAA_LIBRARY_PATH
2022-12-19 20:13:30,333 -WARNING- exit code 127 for CMD 'hmmscan --notextw -E 0.01 --domE 0.01 --noali --domtblout Arabidopsis_suecica_LTR/chunk_aaseq.1.fasta.domtbl /opt/conda/envs/biotools/lib/python3.9/site-packages/TEsorter/database/REXdb_protein_database_viridiplantae_v3.0_plus_metazoa_v3.hmm Arabidopsis_suecica_LTR/chunk_aaseq.1.fasta'
2022-12-19 20:13:30,333 -WARNING- 
	STDOUT:
b''
	STDERR:
b'/bin/sh: 1: hmmscan: not found\n'


2022-12-19 20:13:30,333 -WARNING- exit code 127 for CMD 'hmmscan --notextw -E 0.01 --domE 0.01 --noali --domtblout Arabidopsis_suecica_LTR/chunk_aaseq.2.fasta.domtbl /opt/conda/envs/biotools/lib/python3.9/site-packages/TEsorter/database/REXdb_protein_database_viridiplantae_v3.0_plus_metazoa_v3.hmm Arabidopsis_suecica_LTR/chunk_aaseq.2.fasta'
2022-12-19 20:13:30,333 -WARNING- 
	STDOUT:
b''
	STDERR:
b'/bin/sh: 1: hmmscan: not found\n'


2022-12-19 20:13:30,333 -WARNING- exit code 127 for CMD 'hmmscan --notextw -E 0.01 --domE 0.01 --noali --domtblout Arabidopsis_suecica_LTR/chunk_aaseq.3.fasta.domtbl /opt/conda/envs/biotools/lib/python3.9/site-packages/TEsorter/database/REXdb_protein_database_viridiplantae_v3.0_plus_metazoa_v3.hmm Arabidopsis_suecica_LTR/chunk_aaseq.3.fasta'
2022-12-19 20:13:30,333 -WARNING- 
	STDOUT:
b''
	STDERR:
b'/bin/sh: 1: hmmscan: not found\n'


2022-12-19 20:13:30,333 -WARNING- exit code 127 for CMD 'hmmscan --notextw -E 0.01 --domE 0.01 --noali --domtblout Arabidopsis_suecica_LTR/chunk_aaseq.4.fasta.domtbl /opt/conda/envs/biotools/lib/python3.9/site-packages/TEsorter/database/REXdb_protein_database_viridiplantae_v3.0_plus_metazoa_v3.hmm Arabidopsis_suecica_LTR/chunk_aaseq.4.fasta'
2022-12-19 20:13:30,333 -WARNING- 
	STDOUT:
b''
	STDERR:
b'/bin/sh: 1: hmmscan: not found\n'


 Traceback (most recent call last):
  File "/opt/conda/envs/biotools/bin/TEsorter", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/envs/biotools/lib/python3.9/site-packages/TEsorter/app.py", line 1014, in main
    pipeline(Args())
  File "/opt/conda/envs/biotools/lib/python3.9/site-packages/TEsorter/app.py", line 158, in pipeline
    gff, geneSeq = LTRlibAnn(
  File "/opt/conda/envs/biotools/lib/python3.9/site-packages/TEsorter/app.py", line 912, in LTRlibAnn
    hmmscan_pp(aaSeq, hmmdb=DB[hmmdb], hmmout=domtbl, tmpdir=tmpdir, processors=processors)
  File "/opt/conda/envs/biotools/lib/python3.9/site-packages/TEsorter/app.py", line 888, in hmmscan_pp
    for line in open(domtbl_file):
FileNotFoundError: [Errno 2] No such file or directory: 'Arabidopsis_suecica_LTR/chunk_aaseq.1.fasta.domtbl'
```

**Comment by zhangrengang** [comment]
OK. `hmmscan` should have been installed with `conda install tesorter`.

**Comment by kfuku52** [comment]
I had an old `hmmer` (v2.3) installed in the env to be compatible with `rnammer`. The conda recipe for `tesorter` is probably not checking how old it is.

**Comment by zhangrengang** [comment]
`tesorter` rely on `hmmer>=3.1`.

**Comment by kfuku52** [comment]
Hmm...then no idea how they coexist in the same env...but probably I did some tricky things. Anyway, I will fix it and rerun the Arabidopsis testset.

**Comment by kfuku52** [comment]
SubPhaser successfully finished the test run after upgrading hmmer to v3.3.2. Thank you so much for your help!
`22-12-20 23:10:14 [INFO] Pipeline completed`
