### ISSUE TITLE
ModuleNotFoundError: No module named 'TEsorter'

### ISSUE THREAD

**Issue by dandy3745** [zhangrengang/SubPhaser#17]
Hi, I got module error (No. 1) when I run `subphaser`.
To solve the error, I installed TEsorter using new and old school methods, but subphaser can't find that module.
When I run `from TEsorter.app import CommonClassifications` in python3, I got ImportError (No. 2).
Could you give me the solution? 

Thank you !
Jung

(No. 1)
(SubPhaser)$ subphaser

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/subphaser-1.2.6-py3.8.egg/subphaser/LTR.py", line 9, in <module>
    from TEsorter.app import CommonClassifications
ModuleNotFoundError: No module named 'TEsorter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/subphaser", line 11, in <module>
    load_entry_point('subphaser==1.2.6', 'console_scripts', 'subphaser')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.8/dist-packages/subphaser-1.2.6-py3.8.egg/subphaser/__main__.py", line 15, in <module>
    from . import LTR
  File "/usr/local/lib/python3.8/dist-packages/subphaser-1.2.6-py3.8.egg/subphaser/LTR.py", line 11, in <module>
    from .api.TEsorter.app import CommonClassifications
  File "/usr/local/lib/python3.8/dist-packages/subphaser-1.2.6-py3.8.egg/subphaser/api/TEsorter/app.py", line 37, in <module>
    from .modules.get_record import get_records
  File "/usr/local/lib/python3.8/dist-packages/subphaser-1.2.6-py3.8.egg/subphaser/api/TEsorter/modules/get_record.py", line 6, in <module>
    from TEsorter.modules.small_tools import open_file as open
ModuleNotFoundError: No module named 'TEsorter'

(No. 2)
>>> from TEsorter.app import CommonClassifications
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'CommonClassifications' from 'TEsorter.app' (/home/super/miniconda3/envs/SubPhaser/lib/python3.10/site-packages/TEsorter/app.py)

**Comment by zhangrengang** [comment]
It should be because you installed `subphaser` in `/usr/local/lib/python3.8`, but installed `TEsorter` (and probably other python packages) in `/home/super/miniconda3/envs/SubPhaser/lib/python3.10`. You should install subphaser in the same `/home/super/miniconda3/envs/SubPhaser/lib/python3.10`.

**Comment by dandy3745** [comment]
Thank you for quick reply!

I realized I didn't install using `condo env create -f SubPhaser.yaml`, so I removed env and re-created using `mamba env create -f SubPhaser.yaml`. Unfortunately, I got this error (I also tried to create using `condo env create -f SubPhaser.yaml` too).

Encountered problems while solving:
  - package perl-xml-parser-2.44-4 requires perl >=5.22.0,<5.23.0, but none of the providers can be installed

My perl version is 5.30 and I tried to install perl v5.22.4, but I couldn't solve this error.
Could you give me some solutions? Thank you

Jung

**Comment by zhangrengang** [comment]
@dandy3745 I sorry I have not recieved the email from github.
Can you try the attatched yaml file?
[SubPhaser3.yaml.txt](https://github.com/zhangrengang/SubPhaser/files/10917647/SubPhaser3.yaml.txt)

Alternatively, I think you previously have installed the `env` successly, but just not install subphaser well  via `python setup.py install`.  You shold check `which python` before `python setup.py install`.

**Comment by zhangrengang** [comment]
@dandy3745 I sorry I have not recieved the email from github.
Can you try the attatched yaml file?
[SubPhaser3.yaml.txt](https://github.com/zhangrengang/SubPhaser/files/10917647/SubPhaser3.yaml.txt)

Alternatively, I think you previously have installed the `env` successly, but just not install subphaser well  via `python setup.py install`.  You shold check `which python` before `python setup.py install`.

**Comment by dandy3745** [comment]
Thank you for your reply! 
It worked when I created an environment using `SubPhaser3.yaml`, and `subphaser -h` also worked.

Thank you again!
