### ISSUE TITLE
`TEsorter` cannot find `rexdb` in Singularity container

### ISSUE THREAD

**Issue by taprs** [zhangrengang/SubPhaser#24]
Hi and thanks for the tool! It looks very promising.

I had to use Singularity because of some cluster vs. conda Qt conflicts that I could not resolve. However, with Singularity I found myself unable to proceed beyond the `TEsorter` stage because of the following error:

```
Apptainer> cat /netscratch/dep_mercier/grp_novikova/software/SubPhaser/example_data/tmp/LTR.inner.fa.tesort.log
2023-12-08 17:33:23,593 -INFO- VARS: {'sequence': '/netscratch/dep_mercier/grp_novikova/software/SubPhaser/example_data/tmp/LTR.inner.fa', 'hmm_database': 'rexdb', 'seq_type': 'nucl', 'prefix': '/netscratch/dep_mercier/grp_novikova/software/SubPhaser/example_data/tmp/LTR.inner.fa', 'force_write_hmmscan': False, 'processors': 48, 'tmp_dir': '/netscratch/dep_mercier/grp_novikova/software/SubPhaser/example_data/tmp/LTR', 'min_coverage': 20, 'max_evalue': 0.001, 'disable_pass2': True, 'pass2_rule': '80-80-80', 'no_library': False, 'no_reverse': False, 'no_cleanup': False}
2023-12-08 17:33:23,594 -INFO- checking dependencies:
Traceback (most recent call last):
  File "/share/home/app/bin/miniconda3/envs/SubPhaser/bin/TEsorter", line 10, in <module>
    sys.exit(main())
  File "/share/home/app/bin/miniconda3/envs/SubPhaser/lib/python3.8/site-packages/TEsorter/app.py", line 1014, in main
    pipeline(Args())
  File "/share/home/app/bin/miniconda3/envs/SubPhaser/lib/python3.8/site-packages/TEsorter/app.py", line 145, in pipeline
    Dependency().check_hmmer(db=DB[args.hmm_database])
  File "/share/home/app/bin/miniconda3/envs/SubPhaser/lib/python3.8/site-packages/TEsorter/app.py", line 952, in check_hmmer
    dp_version = self.get_hmm_version(db)[:3]
  File "/share/home/app/bin/miniconda3/envs/SubPhaser/lib/python3.8/site-packages/TEsorter/app.py", line 967, in get_hmm_version
    line = open(db).readline()
**FileNotFoundError: [Errno 2] No such file or directory: '/share/home/app/bin/miniconda3/envs/SubPhaser/lib/python3.8/site-packages/TEsorter/database/REXdb_protein_database_viridiplantae_v3.0_plus_metazoa_v3.hmm'**
```

Turns out `databases` are not loaded at all:

```
Apptainer> ls /share/home/app/bin/miniconda3/envs/SubPhaser/lib/python3.8/site-packages/TEsorter/
__init__.py  __main__.py  app.py       modules/     version.py
```

How would I fix that?

Cheers,
Nikita

**Comment by zhangrengang** [comment]
I am sorry for this issue. If you are able to re-build the container, you can install `TEsorter`  via conda, then copy the `database` into the container, and re-build finally. Alternatively, I will update the image file in a few days.

**Comment by zhangrengang** [comment]
@taprs We have updated the container file. You may `apptainer pull --arch amd64 library://shang-hongyun/collection/subphaser.sif:1.2.6` and retry.

**Comment by taprs** [comment]
The fix solved the issue, thank you very much for the prompt help!
