### ISSUE TITLE
ValueError: All singletons are not allowed

### ISSUE THREAD

**Issue by z626093820** [zhangrengang/SubPhaser#27]
when I use the command subphaser -i brg.fa -c brg.txt ,it show the error  ValueError: All singletons are not allowed

how can I slove? Thanks!

Traceback (most recent call last):
  File "/home/zuozd/miniconda3/envs/SubPhaser/bin/subphaser", line 33, in <module>
    sys.exit(load_entry_point('subphaser==1.2.6', 'console_scripts', 'subphaser')())
  File "/home/zuozd/miniconda3/envs/SubPhaser/lib/python3.8/site-packages/subphaser-1.2.6-py3.8.egg/subphaser/__main__.py", line 797, in main
    pipeline.run()
  File "/home/zuozd/miniconda3/envs/SubPhaser/lib/python3.8/site-packages/subphaser-1.2.6-py3.8.egg/subphaser/__main__.py", line 422, in run
    d_mat = dumps.filter(d_mat, lengths, self.sgs, outfig=histfig, #d_targets=d_targets,
  File "/home/zuozd/miniconda3/envs/SubPhaser/lib/python3.8/site-packages/subphaser-1.2.6-py3.8.egg/subphaser/Jellyfish.py", line 479, in filter
    raise ValueError('All singletons are not allowed')
ValueError: All singletons are not allowed

**Comment by z626093820** [comment]
The issue occurred due to the use of an incorrect configuration file.
