### ISSUE TITLE
ValueError: 0 kmer with fold > 2. Please reset the filter options.

### ISSUE THREAD

**Issue by z626093820** [zhangrengang/SubPhaser#28]
When I analyze using the default parameters, the following error occurs. What should I set the kmer parameters to?

23-12-30 15:24:20 [INFO] After filtering, remained 0 (0.00%) differential (freq >= 200) and 0 (0.00%) candidate (freq > 0) kmers
Traceback (most recent call last):
  File "/home/zuozd/miniconda3/envs/SubPhaser/bin/subphaser", line 33, in <module>
    sys.exit(load_entry_point('subphaser==1.2.6', 'console_scripts', 'subphaser')())
  File "/home/zuozd/miniconda3/envs/SubPhaser/lib/python3.8/site-packages/subphaser-1.2.6-py3.8.egg/subphaser/__main__.py", line 797, in main
    pipeline.run()
  File "/home/zuozd/miniconda3/envs/SubPhaser/lib/python3.8/site-packages/subphaser-1.2.6-py3.8.egg/subphaser/__main__.py", line 422, in run
    d_mat = dumps.filter(d_mat, lengths, self.sgs, outfig=histfig, #d_targets=d_targets,
  File "/home/zuozd/miniconda3/envs/SubPhaser/lib/python3.8/site-packages/subphaser-1.2.6-py3.8.egg/subphaser/Jellyfish.py", line 502, in filter
    raise ValueError('0 kmer with fold > {}. Please reset the filter options.'.format(min_fold))
ValueError: 0 kmer with fold > 2. Please reset the filter options.

THANK YOU!

**Comment by zhangrengang** [comment]
Because there is no candidate (freq > 0) kmers, resetting parameters may not work. Please refer to #26 .
