### ISSUE TITLE
OSError: [Errno 12] Cannot allocate memory

### ISSUE THREAD

**Issue by GLking123** [zhangrengang/SubPhaser#35]
张老师 你好！
判断超大基因组（50G）是否为异源或者同源染色体,集群内存5T,
最近运行总是报错，运行命令如下：
`subphaser -i part1.fasta -c new_1.config -lower_count 3 -pre Al_out > Al.log` 
报错信息如下：
`24-08-06 23:49:35 [INFO] Filtering differential kmers
Traceback (most recent call last):
  File "/public/home/zengpeng/environment/SubPhaser/bin/subphaser", line 33, in <module>
    sys.exit(load_entry_point('subphaser==1.2.6', 'console_scripts', 'subphaser')())
  File "/public/home/zengpeng/environment/SubPhaser/lib/python3.8/site-packages/subphaser-1.2.6-py3.8.egg/subphaser/__main__.py", line 797, in main
    pipeline.run()
  File "/public/home/zengpeng/environment/SubPhaser/lib/python3.8/site-packages/subphaser-1.2.6-py3.8.egg/subphaser/__main__.py", line 422, in run
    d_mat = dumps.filter(d_mat, lengths, self.sgs, outfig=histfig, #d_targets=d_targets, 
  File "/public/home/zengpeng/environment/SubPhaser/lib/python3.8/site-packages/subphaser-1.2.6-py3.8.egg/subphaser/Jellyfish.py", line 491, in filter
    for kmer, freqs, tot_freq in pool_func(_filter_kmer, args, self.ncpu, 
  File "/public/home/zengpeng/environment/SubPhaser/lib/python3.8/site-packages/subphaser-1.2.6-py3.8.egg/subphaser/RunCmdsMP.py", line 336, in pool_func
    pool = multiprocessing.Pool(processors)
  File "/public/home/zengpeng/environment/SubPhaser/lib/python3.8/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/public/home/zengpeng/environment/SubPhaser/lib/python3.8/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/public/home/zengpeng/environment/SubPhaser/lib/python3.8/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/public/home/zengpeng/environment/SubPhaser/lib/python3.8/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/public/home/zengpeng/environment/SubPhaser/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/public/home/zengpeng/environment/SubPhaser/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/public/home/zengpeng/environment/SubPhaser/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/public/home/zengpeng/environment/SubPhaser/lib/python3.8/multiprocessing/popen_fork.py", line 70, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
` 
我该使用什么命令去调试，使得软件顺利运行，我尝试切割前16个染色体，但是还是同样的错误。

**Comment by zhangrengang** [comment]
可以尝试-lower_count 10 -q 200减少kmer数量。
如果TE分布均匀，确实也可以切割染色体，每条染色体上只取一段（比如100Mb），这样能得到染色体所属亚基因组，但无法全面鉴定亚基因组间的exchange。

2024-08-07 17:32:42"jenny315" ***@***.***>写道：

张老师 您好！
判断超大基因组（50G）是否为异源或者同源染色体,集群内存5T,
最近运行总是报错，运行命令如下：
subphaser -i part1.fasta -c new_1.config -lower_count 3 -pre Al_out > Al.log
报错信息如下：
24-08-06 23:49:35 [INFO] Filtering differential kmers Traceback (most recent call last): File "/public/home/zengpeng/environment/SubPhaser/bin/subphaser", line 33, in <module> sys.exit(load_entry_point('subphaser==1.2.6', 'console_scripts', 'subphaser')()) File "/public/home/zengpeng/environment/SubPhaser/lib/python3.8/site-packages/subphaser-1.2.6-py3.8.egg/subphaser/__main__.py", line 797, in main pipeline.run() File "/public/home/zengpeng/environment/SubPhaser/lib/python3.8/site-packages/subphaser-1.2.6-py3.8.egg/subphaser/__main__.py", line 422, in run d_mat = dumps.filter(d_mat, lengths, self.sgs, outfig=histfig, #d_targets=d_targets, File "/public/home/zengpeng/environment/SubPhaser/lib/python3.8/site-packages/subphaser-1.2.6-py3.8.egg/subphaser/Jellyfish.py", line 491, in filter for kmer, freqs, tot_freq in pool_func(_filter_kmer, args, self.ncpu, File "/public/home/zengpeng/environment/SubPhaser/lib/python3.8/site-packages/subphaser-1.2.6-py3.8.egg/subphaser/RunCmdsMP.py", line 336, in pool_func pool = multiprocessing.Pool(processors) File "/public/home/zengpeng/environment/SubPhaser/lib/python3.8/multiprocessing/context.py", line 119, in Pool return Pool(processes, initializer, initargs, maxtasksperchild, File "/public/home/zengpeng/environment/SubPhaser/lib/python3.8/multiprocessing/pool.py", line 212, in __init__ self._repopulate_pool() File "/public/home/zengpeng/environment/SubPhaser/lib/python3.8/multiprocessing/pool.py", line 303, in _repopulate_pool return self._repopulate_pool_static(self._ctx, self.Process, File "/public/home/zengpeng/environment/SubPhaser/lib/python3.8/multiprocessing/pool.py", line 326, in _repopulate_pool_static w.start() File "/public/home/zengpeng/environment/SubPhaser/lib/python3.8/multiprocessing/process.py", line 121, in start self._popen = self._Popen(self) File "/public/home/zengpeng/environment/SubPhaser/lib/python3.8/multiprocessing/context.py", line 277, in _Popen return Popen(process_obj) File "/public/home/zengpeng/environment/SubPhaser/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__ self._launch(process_obj) File "/public/home/zengpeng/environment/SubPhaser/lib/python3.8/multiprocessing/popen_fork.py", line 70, in _launch self.pid = os.fork() OSError: [Errno 12] Cannot allocate memory
我该使用什么命令去调试，使得软件顺利运行，我尝试切割前16个染色体，但是还是同样的错误。

**Comment by GLking123** [comment]
好的，张老师，现在按照您的放大，在进行尝试。
