### ISSUE TITLE
OSError: /usr/lib/libdrmaa.so.1.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by emircankaaya** [zhangrengang/SubPhaser#36]
![Ekran Alıntısı](https://github.com/user-attachments/assets/2ec5a100-d8d7-41a9-bc36-5475c0019067)
I try to run SubPhaser but I faced with this error. I use Python 3.8.8 on Ubuntu as Windows Subsystem.

Dear Dr., Could you please help me?

![Ekran Alıntısı](https://github.com/user-attachments/assets/43373bc4-16a2-4922-8069-40ced4ec44fc)
(SubPhaser) eck@DESKTOP-ED16O0T:~/SubPhaser$ subphaser -i genome.fasta.gz -c sg.config
24-08-10 15:19:34 [WARNING] Grid computing is not available because DRMAA not installed: /usr/lib/libdrmaa.so.1.0: cannot open shared object file: No such file or directory
24-08-10 15:19:34 [INFO] No DRMAA (see https://github.com/pygridtools/drmaa-python), Switching to local mode.
Traceback (most recent call last):
  File "/home/eck/miniconda3/envs/SubPhaser/bin/subphaser", line 33, in <module>
    sys.exit(load_entry_point('subphaser==1.2.6', 'console_scripts', 'subphaser')())
  File "/home/eck/miniconda3/envs/SubPhaser/bin/subphaser", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/eck/miniconda3/envs/SubPhaser/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/home/eck/miniconda3/envs/SubPhaser/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/eck/miniconda3/envs/SubPhaser/lib/python3.8/site-packages/subphaser-1.2.6-py3.8.egg/subphaser/__main__.py", line 15, in <module>
    from . import LTR
  File "/home/eck/miniconda3/envs/SubPhaser/lib/python3.8/site-packages/subphaser-1.2.6-py3.8.egg/subphaser/LTR.py", line 9, in <module>
    from TEsorter.app import CommonClassifications
  File "/home/eck/miniconda3/envs/SubPhaser/lib/python3.8/site-packages/TEsorter/app.py", line 30, in <module>
    from .modules.RunCmdsMP import run_cmd, pp_run, pool_func
  File "/home/eck/miniconda3/envs/SubPhaser/lib/python3.8/site-packages/TEsorter/modules/RunCmdsMP.py", line 24, in <module>
    import drmaa    # for grid
  File "/home/eck/miniconda3/envs/SubPhaser/lib/python3.8/site-packages/drmaa/__init__.py", line 65, in <module>
    from .session import JobInfo, JobTemplate, Session
  File "/home/eck/miniconda3/envs/SubPhaser/lib/python3.8/site-packages/drmaa/session.py", line 39, in <module>
    from drmaa.helpers import (adapt_rusage, Attribute, attribute_names_iterator,
  File "/home/eck/miniconda3/envs/SubPhaser/lib/python3.8/site-packages/drmaa/helpers.py", line 36, in <module>
    from drmaa.wrappers import (drmaa_attr_names_t, drmaa_attr_values_t,
  File "/home/eck/miniconda3/envs/SubPhaser/lib/python3.8/site-packages/drmaa/wrappers.py", line 56, in <module>
    _lib = CDLL(libpath, mode=RTLD_GLOBAL)
  File "/home/eck/miniconda3/envs/SubPhaser/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/libdrmaa.so.1.0: cannot open shared object file: No such file or directory

**Comment by zhangrengang** [comment]
In File "/home/eck/miniconda3/envs/SubPhaser/lib/python3.8/site-packages/TEsorter/modules/RunCmdsMP.py", lines 25 - 28, there should be a line `except (RuntimeError,ImportError,AttributeError,OSError) as e:` which could ignore the `OSError`. If not, please show me the code of lines 20 - 40 of `/home/eck/miniconda3/envs/SubPhaser/lib/python3.8/site-packages/TEsorter/modules/RunCmdsMP.py`.
Which version of your `TEsorter`?

2024-08-10 20:23:37"jenny315" ***@***.***>写道：

Ekran.Alintisi.PNG (view on web)
I try to run SubPhaser but I faced with this error. I use Python 3.8.8 on Ubuntu as Windows Subsystem.

Dear Dr., Could you please help me?

Ekran.Alintisi.PNG (view on web)
(SubPhaser) ***@***.***:~/SubPhaser$ subphaser -i genome.fasta.gz -c sg.config
24-08-10 15:19:34 [WARNING] Grid computing is not available because DRMAA not installed: /usr/lib/libdrmaa.so.1.0: cannot open shared object file: No such file or directory
24-08-10 15:19:34 [INFO] No DRMAA (see https://github.com/pygridtools/drmaa-python), Switching to local mode.
Traceback (most recent call last):
File "/home/eck/miniconda3/envs/SubPhaser/bin/subphaser", line 33, in
sys.exit(load_entry_point('subphaser==1.2.6', 'console_scripts', 'subphaser')())
File "/home/eck/miniconda3/envs/SubPhaser/bin/subphaser", line 25, in importlib_load_entry_point
return next(matches).load()
File "/home/eck/miniconda3/envs/SubPhaser/lib/python3.8/importlib/metadata.py", line 77, in load
module = import_module(match.group('module'))
File "/home/eck/miniconda3/envs/SubPhaser/lib/python3.8/importlib/init.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 1014, in _gcd_import
File "", line 991, in _find_and_load
File "", line 975, in _find_and_load_unlocked
File "", line 671, in _load_unlocked
File "", line 783, in exec_module
File "", line 219, in _call_with_frames_removed
File "/home/eck/miniconda3/envs/SubPhaser/lib/python3.8/site-packages/subphaser-1.2.6-py3.8.egg/subphaser/main.py", line 15, in
from . import LTR
File "/home/eck/miniconda3/envs/SubPhaser/lib/python3.8/site-packages/subphaser-1.2.6-py3.8.egg/subphaser/LTR.py", line 9, in
from TEsorter.app import CommonClassifications
File "/home/eck/miniconda3/envs/SubPhaser/lib/python3.8/site-packages/TEsorter/app.py", line 30, in
from .modules.RunCmdsMP import run_cmd, pp_run, pool_func
File "/home/eck/miniconda3/envs/SubPhaser/lib/python3.8/site-packages/TEsorter/modules/RunCmdsMP.py", line 24, in
import drmaa # for grid
File "/home/eck/miniconda3/envs/SubPhaser/lib/python3.8/site-packages/drmaa/init.py", line 65, in
from .session import JobInfo, JobTemplate, Session
File "/home/eck/miniconda3/envs/SubPhaser/lib/python3.8/site-packages/drmaa/session.py", line 39, in
from drmaa.helpers import (adapt_rusage, Attribute, attribute_names_iterator,
File "/home/eck/miniconda3/envs/SubPhaser/lib/python3.8/site-packages/drmaa/helpers.py", line 36, in
from drmaa.wrappers import (drmaa_attr_names_t, drmaa_attr_values_t,
File "/home/eck/miniconda3/envs/SubPhaser/lib/python3.8/site-packages/drmaa/wrappers.py", line 56, in
_lib = CDLL(libpath, mode=RTLD_GLOBAL)
File "/home/eck/miniconda3/envs/SubPhaser/lib/python3.8/ctypes/init.py", line 373, in init
self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/libdrmaa.so.1.0: cannot open shared object file: No such file or directory
